#!/bin/bash
docker context use pakastin
docker build --tag ghcr.io/pakastin/datacentertest .
docker push ghcr.io/pakastin/datacentertest
docker service update --image ghcr.io/pakastin/datacentertest pakastin_datacentertest
